const dummyUser = [
  {
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'password123',
    image: '/images/users/alice.png',
    phone: '+1-1234567890',
    address: '123 Maple St, Springfield, IL',
    isAdmin: false,
    isBanned: false,
  },
  {
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    password: 'mypassword',
    image: '/images/users/bob.png',
    phone: '+44-2081234567',
    address: '456 Oak St, London, UK',
    isAdmin: false,
    isBanned: false,
  },
  {
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    password: 'securepassword',
    image: '/images/users/charlie.png',
    phone: '+91-9876543210',
    address: '789 Pine St, Mumbai, India',
    isAdmin: false,
    isBanned: false,
  },
  {
    name: 'Dana Prince',
    email: 'dana.prince@example.com',
    password: 'wonderwoman',
    image: '/images/users/diana.png',
    phone: '+61-412345678',
    address: '1010 Willow St, Sydney, Australia',
    isAdmin: false,
    isBanned: false,
  },
  {
    name: 'Alko Johnson',
    email: 'alko.johnson@example.com',
    password: 'password123',
    image: '/images/users/alice.png',
    phone: '+1-8934567890',
    address: '123 Maple St, Springfield, IL',
    isAdmin: false,
    isBanned: false,
  },
  {
    name: 'Body Smith',
    email: 'Body.smith@example.com',
    password: 'mypassword',
    image: '/images/users/bob.png',
    phone: '+44-2241234567',
    address: '456 Oak St, London, UK',
    isAdmin: true,
    isBanned: false,
  },
  {
    name: 'marki Brown',
    email: 'marki.brown@example.com',
    password: 'securepassword',
    image: '/images/users/charlie.png',
    phone: '+91-6576543210',
    address: '789 Pine St, Mumbai, India',
    isAdmin: false,
    isBanned: true,
  },
  {
    name: 'Diana Prince',
    email: 'diana.prince@example.com',
    password: 'wonderwoman',
    image: '/images/users/diana.png',
    phone: '+61-412345678',
    address: '1010 Willow St, Sydney, Australia',
    isAdmin: false,
    isBanned: false,
  },
];
module.exports = dummyUser;
